app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#save_measurement:
#    path: /measurement
#    defaults: { _controller: AppBundle:Default:saveMeasurement }
#    requirements:
#        method: POST
